// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HuntingDog
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HuntingDogPackageIDString = "5b3a5944-ba3e-449d-8b79-4d194244b643";
        public const string HuntingDogIconsString = "245dd7ad-f68d-4b2a-9163-91cba9070323";
        public const string HuntingDogCommandSetIDString = "c2de79ab-b0ac-40bf-b340-34c6ab2bff53";
        public static Guid HuntingDogPackageID = new Guid(HuntingDogPackageIDString);
        public static Guid HuntingDogIcons = new Guid(HuntingDogIconsString);
        public static Guid HuntingDogCommandSetID = new Guid(HuntingDogCommandSetIDString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int HuntingDogPaw = 0x0001;
        public const int HuntingDogMenuGroup = 0x1020;
        public const int HuntingDogCommandId = 0x0100;
    }
}
